name: Docs

on:
  push:
    branches: [ develop, release ]
    paths:
    - 'docs/**'
    - 'docs_theme/**'
    - 'mkdocs.yml'
    - 'readthedocs.yml'
    - '.github/workflows/docs.yaml'
  pull_request:
    branches: [ develop ]
    paths:
    - 'docs/**'
    - 'docs_theme/**'
    - 'mkdocs.yml'
    - 'readthedocs.yml'
    - '.github/workflows/docs.yaml'

jobs:
  accessibility:
    if: contains(toJson(github.event.commits), '[ci skip]') == false
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Setup Node.js environment
      uses: actions/setup-node@main

    - name: poetry cache
      uses: actions/cache@v2
      with:
        path: .venv
        key: ${{ runner.os }}-${{ hashFiles('poetry.lock') }}-${{ matrix.python-version }}

    - name: npm cache
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-pa11y-v3

    - name: Install dependencies
      run: |
        pip install poetry
        poetry config --local virtualenvs.in-project true
        poetry install --no-root --remove-untracked
        npm install pa11y-ci
        echo "node_modules/.bin" >> $GITHUB_PATH

    - name: Start docs server
      run: poetry run mkdocs serve &

    - name: Generate sitemap
      env:
        site_url: http://127.0.0.1:8000
      run: |
        select="{urls: [\"${site_url}/\", \"${site_url}/search.html?q=jrnl\", .urlset.url[].loc]}"
        curl -s "$site_url/sitemap.xml" | poetry run xq "$select" > list.json

    - name: Accessibility testing (Pa11y)
      run: pa11y-ci -c list.json
