name: Docs

on:
  push:
    branches: [ develop, release ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Setup Node.js environment
      uses: actions/setup-node@main

    - name: poetry cache
      uses: actions/cache@v2
      with:
        path: .venv
        key: ${{ runner.os }}-${{ hashFiles('poetry.lock') }}-${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install poetry
        poetry config --local virtualenvs.in-project true
        poetry install --no-root --remove-untracked
        npm install pa11y

    - name: Start docs server
      run: poetry run mkdocs serve &

    - name: Accessibility testing (Pa11y)
      run: poetry run .github/workflows/pa11y.sh

