# Copyright © 2012-2023 jrnl contributors
# License: https://www.gnu.org/licenses/gpl-3.0.html

name: Testing

on:
  schedule:
    - cron: '0 0 * * SAT'

defaults:
  run:
    shell: bash # needed to prevent Windows from using PowerShell

jobs:
  test_all:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.10', '3.11', '3.12' ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - name: Run tests
        uses: ./.github/actions/run_tests
        with:
          cache-string: ${{ secrets.CACHE_STRING }}
