name: Testing

on:
  schedule:
    - cron: '0 0 * * SAT'

defaults:
  run:
    shell: bash # needed to prevent Windows from using PowerShell

jobs:
  test_all:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.7, 3.8, 3.9, '3.10', 3.11-dev ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        uses: ./.github/actions/run_tests
        with:
          cache-string: ${{ secrets.CACHE_STRING }}
