name: Testing

on:
  schedule:
    - cron: '0 0 * * SAT'

defaults:
  run:
    shell: bash # needed to prevent Windows from using PowerShell

jobs:
  test_all:
    if: >
      ! contains(github.event.head_commit.message, '[ci skip]')
      github.event_name == 'schedule'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.7, 3.8, 3.9, '3.10', 3.11-dev ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - uses: ./.github/actions/run_tests
