# Copyright © 2012-2023 jrnl contributors
# License: https://www.gnu.org/licenses/gpl-3.0.html

name: Testing Pipeline Files

on:
  push:
    branches: [ develop, release ]
    paths:
    - '.github/workflows/**'
    - '.github/actions/**'
  pull_request:
    branches: [ develop ]
    paths:
    - '.github/workflows/**'
    - '.github/actions/**'
  schedule:
    - cron: '0 0 * * SAT'

jobs:
  test:
    if: >
      ! contains(github.event.head_commit.message, '[ci skip]')
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - name: Check workflow files
        uses: docker://rhysd/actionlint:latest
        with:
          args: -color
